name: imguru
on: [push]

jobs:
  build:
    name: imguru
    timeout-minutes: 60
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Run script"
        run: ./ci/mac/build.sh
        shell: bash
        env:
          APPLICATION: ${{ secrets.APPLICATION }}
          INSTALLER: ${{ secrets.INSTALLER }}
          APPLE_PASS: ${{ secrets.APPLE_PASS }}
          APPLE_USER: ${{ secrets.APPLE_USER }}
      - uses: actions/upload-artifact@v1
        with:
          name: imguru
          path: ci/mac/bin

